# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/j39950/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/j39950/Desktop/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/j39950/Desktop/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {{C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/mfp_ahb_const.vh}}
set_property file_type "Verilog Header" [get_files {{C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/mfp_ahb_const.vh}}]
read_verilog -library xil_defaultlib {
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/gp.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/add.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/cla_2.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/cla_4.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/cla_8.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/cla_16.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/rtl/aes_sbox.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/rtl/aes_rcon.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/cla_32.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/rtl/aes_key_expand_128.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/cla32.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/rtl/gfm128_16.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/rtl/aes_cipher_top.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/shift.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/sevensegdec.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/mux4x32.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/addsub32.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/new/seqram.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/new/gcm_aes_controller.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/new/dff128.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/rtl/gcm_aes_v0.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/spi_interface.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/sevensegtimer.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/regfile.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/mux2x5.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/mux2x32.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/milliscounter.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/mccu.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/dffe32.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/dffe128.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/dff32.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/buzzer.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/alu.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/Common/sigram.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/new/mcgpio.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/new/mccomp_decoder.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/mccpu.v}
  C:/Users/j39950/Desktop/Common/uram.v
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/mccomp_sys.v}
  {C:/Users/j39950/Desktop/Multi Cycle/mccompFPGA.srcs/sources_1/imports/mccompFPGA/mfp_nexys4_ddr.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top mfp_nexys4_ddr -part xc7a200tfbg676-2


write_checkpoint -force -noxdef mfp_nexys4_ddr.dcp

catch { report_utilization -file mfp_nexys4_ddr_utilization_synth.rpt -pb mfp_nexys4_ddr_utilization_synth.pb }
